---
- name: install rambox
  sudo: true

  when: ansible_machine == "x86"
  apt: 
    install_recommends: yes
    deb: https://github.com/ramboxapp/community-edition/releases/download/0.6.4/Rambox-0.6.4-linux-i386.deb

  when: ansible_machine == "x86_64"
  apt: 
    install_recommends: yes
    deb: https://github.com/ramboxapp/community-edition/releases/download/0.6.4/Rambox-0.6.4-linux-amd64.deb


  

  