---
- name: install spotify
- sudo: true

   lxc_container: 
      template: ubuntu
      container_command: 
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 -- recv-key 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
        echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/source.list.d/spotify.list
        sudo apt-get update
        sudo apt-get install spotify-client
        state: present


